---
title: "Model_EDA"
format: html
editor: visual
---

# Spatial Temporal SVR result analysis

## Result for first 3 area

```{r}
top_msoa <- test_results %>%
  group_by(.data[[cscale]]) %>%
  summarise(total = sum(Actual)) %>%
  arrange(desc(total)) %>%
  slice(1:3) %>%
  pull(.data[[cscale]])

plot_subset <- test_results %>%
  filter(.data[[cscale]] %in% top_msoa)

ggplot(plot_subset, aes(x = time_date)) +
  geom_line(aes(y = Actual, group = .data[[cscale]], color = .data[[cscale]]), size = 0.5) +
  geom_line(aes(y = Predicted, group = .data[[cscale]], color = .data[[cscale]]), linetype = "dashed", size = 0.8) +
  facet_wrap(~.data[[cscale]], scales = "free_y", ncol = 1) +
  theme_minimal()
```

## Plot result

```{r}
analyse_final <- test_results%>%
  group_by(.data[[cscale]])%>%
  summarise(total_actual = sum(Actual), total_predicted = sum(Predicted))
analyse_final_all <- test_results%>%
  mutate(
    mse = (Actual - Predicted)^2,
    mse_t = (Actual - Predicted_t)^2)%>%
  left_join(london_geom, by = cscale)%>%
  st_as_sf()

predicted_line <- test_results%>%
  group_by(time_date)%>%
  summarise(
    total_actual = sum(Actual), total_predicted = sum(Predicted), total_predicted_t = sum(Predicted_t))%>%
  ggplot(aes(x = time_date)) +
  geom_line(aes(y = total_actual, color = "Actual"), size = 0.5) +
  geom_line(aes(y = total_predicted, color = "Predicted"), linetype = "dashed", size = 0.8) +
  geom_line(aes(y = total_predicted_t, color = "Predicted_t"), linetype = "dashed", size = 0.8) +
  theme_minimal() +
  labs(title = "Total Actual vs Predicted Accidents Over Time", y = "Total Accidents", color = "Legend")
predicted_line
# ggsave(file = "Data/Layout/ST_SVR_result.png", predicted_line, width = 15, height = 6, dpi = 300)
```

## Residual

```{r}
mse_plot <- analyse_final_all%>%
  ggplot()+
  geom_line(aes(time_date, mse)) +
  theme_minimal() +
  labs(title = "MSE of SVR with Spatial Lag Over Time", x = "Time", y = "Mean Squared Error")
mse_plot
# ggsave(file = "Data/Layout/ST_SVR_mse.png", mse_plot, width = 15, height = 6, dpi = 300)
```

## Map

```{r}
library(tmap)
source('../utils/map_func.R')
spatial_error <- analyse_final_all %>%
  group_by(.data[[cscale]]) %>%
  summarise(
    avg_residual = mean(Actual - Predicted, na.rm = TRUE),
    geometry = st_union(geometry)) %>%
  st_as_sf()

tmap_mode('plot')
error_map <- tm_basemap("CartoDB.Positron") +
  tm_shape(spatial_error) +
  tm_polygons(
    fill = "avg_residual",
    # fill.scale = tm_scale_intervals(
    #   values = "RdBu",
    #   midpoint = 0,
    #   style = "fixed",
    #   breaks = c(-Inf, -10, -5, -2, 2, 5, 10, Inf)),
    fill.legend = tm_legend(title = "Avg Residual (Actual - Predicted)")) +
  add_map_decorations()

error_map
# tmap_save(error_map, filename = paste0("Data/Layout/residual_map_",cscale,".png", sep=''), width = 12, height = 6, dpi = 300)
```

# Spatial Temporal ARIMA result analysis

```{r}
hist(fit.star$RES[,1], main="Residuals for First Area")
Box.test(fit.star$RES[,1], lag=1, type="Ljung")
```

## Plot result

```{r}
matplot(cbind(pre.star$OBS[,2], pre.star$PRE[,2]), 
        type="l", lty=c(1,2), col=c("black", "red"),
        main="STARIMA: Actual (Black) vs Predicted (Red)")
```

# ST GCN

```{r}
top_msoa <- test_results_stgcn %>%
  group_by(.data[[cscale]]) %>%
  summarise(total = sum(Actual)) %>%
  arrange(desc(total)) %>%
  slice(1:3) %>%
  pull(.data[[cscale]])

plot_subset <- test_results_stgcn %>%
  filter(.data[[cscale]] %in% top_msoa)

ggplot(plot_subset, aes(x = time_date)) +
  geom_line(aes(y = Actual, group = .data[[cscale]], color = .data[[cscale]]), size = 0.5) +
  geom_line(aes(y = Predicted, group = .data[[cscale]], color = .data[[cscale]]), linetype = "dashed", size = 0.8) +
  facet_wrap(~.data[[cscale]], scales = "free_y", ncol = 1) +
  theme_minimal()
```

```{r}
analyse_final <- test_results_stgcn%>%
  group_by(.data[[cscale]])%>%
  summarise(total_actual = sum(Actual), total_predicted = sum(Predicted))
analyse_final_all_gcn <- test_results_stgcn%>%
  mutate(
    mse = (Actual - Predicted)^2,
    mse_t = (Actual - Predicted_t)^2)%>%
  left_join(london_geom, by = cscale)%>%
  st_as_sf()

predicted_line <- test_results_stgcn%>%
  group_by(time_date)%>%
  summarise(
    total_actual = sum(Actual), total_predicted = sum(Predicted), total_predicted_t = sum(Predicted_t))%>%
  ggplot(aes(x = time_date)) +
  geom_line(aes(y = total_actual, color = "Actual"), size = 0.5) +
  geom_line(aes(y = total_predicted, color = "Predicted"), linetype = "dashed", size = 0.8) +
  geom_line(aes(y = total_predicted_t, color = "Predicted_t"), linetype = "dashed", size = 0.8) +
  theme_minimal() +
  labs(title = "Total Actual vs Predicted Accidents Over Time", y = "Total Accidents", color = "Legend")
predicted_line
```

# Compare Three models

```{r}
actual_mat <- as.matrix(test_Z)
pred_mat <- as.matrix(pre.star$PRE)
n_rows <- min(nrow(actual_mat), nrow(pred_mat))

diff_mat <- tail(actual_mat, n_rows) - tail(pred_mat, n_rows)

star_mse_vec <- colMeans(diff_mat^2, na.rm = TRUE)

starima_metrics <- data.frame(
  lad22cd = names(star_mse_vec),
  # msoa21cd = names(star_mse_vec),
  mse_star = star_mse_vec)

stsvr_metrics <- analyse_final_all %>%
  st_drop_geometry() %>%
  group_by(!!sym(cscale)) %>%
  summarise(mse_svr = mean(mse, na.rm = TRUE))

model_comparison <- stsvr_metrics %>%
  left_join(starima_metrics, by = cscale)

stgcn_metrics <- analyse_final_all_gcn %>%
  st_drop_geometry() %>%
  group_by(!!sym(cscale)) %>%
  summarise(mse_svr = mean(mse, na.rm = TRUE))

# model_comparison %>% st_drop_geometry()
```

## MSE compare through different area

```{r}
library(forcats)
plot_data <- model_comparison %>%
  # reorder lad22cd based on mse_scr
  mutate(lad22cd = fct_reorder(lad22cd, mse_svr)) %>%
  # mutate(msoa21cd = fct_reorder(msoa21cd, mse_svr)) %>%
  pivot_longer(cols = c(mse_svr, mse_star), 
               names_to = "Model", 
               values_to = "MSE") %>%
  mutate(Model = ifelse(Model == "mse_svr", "SVR", "STARIMA"))

area_compare <- ggplot(plot_data, aes(x = MSE, y = .data[[cscale]])) +
  geom_line(aes(group = .data[[cscale]]), color = "gray80", size = 1) +
  geom_point(aes(color = Model), size = 1) +
  labs(title = "MSE by District: STSVR vs STARIMA",
       x = "Mean Squared Error (MSE)",
       y = "District Code")

area_compare
# ggsave(file = "../Data/Layout/area_based_two_model_compare.png", area_compare, width = 8, height = 6, dpi = 300)
```

```{r}

test_results_combined <- test_results %>%
  mutate(
    Predicted_GCN = test_results_stgcn$Predicted,
    Predicted_T_GCN = test_results_stgcn$Predicted_t
  )
aggregate_all_models <- test_results_combined %>%
  mutate(
    mse = (Predicted - Actual)^2,
    mse_t = (Predicted_t - Actual)^2, 
    mse_gcn = (Predicted_GCN - Actual)^2, 
    mse_t_gcn = (Predicted_T_GCN - Actual)^2) %>%
  group_by(time_date) %>%
  summarise(
    actual_sum = sum(Actual), 
    mse_stsvr = mean(mse), predict_stsvr = sum(Predicted),
    mse_tsvr = mean(mse_t), predict_tsvr = sum(Predicted_t),
    mse_stgcn = mean(mse_gcn), predict_stgcn = sum(Predicted_GCN),
    mse_tgcn = mean(mse_t_gcn), predict_tgcn = sum(Predicted_T_GCN)) %>%
  slice(-1) %>%
  mutate(
    predict_starima = predict_starima, mse_starima = mse_per_time,
    predict_arima = predict_arima, mse_arima = pred_se
  )


avg_mse_svr <- round(mean(aggregate_all_models$mse_stsvr, na.rm = TRUE), 2)
avg_mse_tsvr <- round(mean(aggregate_all_models$mse_tsvr, na.rm = TRUE), 2)
avg_mse_starima <- round(mean(aggregate_all_models$mse_starima, na.rm = TRUE), 2)
avg_mse_arima <- round(mean(aggregate_all_models$mse_arima, na.rm = TRUE), 2)
avg_mse_stgcn <- round(mean(aggregate_all_models$mse_stgcn, na.rm = TRUE), 2)
avg_mse_tgcn <- round(mean(aggregate_all_models$mse_tgcn, na.rm = TRUE), 2)

mse_label <- paste0("STSVR MSE: ", avg_mse_svr, 
                    "  |  TSVR MSE: ", avg_mse_tsvr,
                    "  |  STARIMA MSE: ", avg_mse_starima, '\n',
                    " ARIMA MSE: ", avg_mse_arima,
                    "  |  STGCN MSE: ", avg_mse_stgcn,
                    "  |  TGCN MSE: ", avg_mse_tgcn)

compare_plot <- aggregate_all_models %>%
  ggplot() +
  geom_line(aes(x=time_date, y=actual_sum, color="Actual"), size=1) +
  geom_line(aes(x=time_date, y=predict_stsvr, color="STSVR"), size=1, linetype = "dashed") +
  geom_line(aes(x=time_date, y=predict_tsvr, color="TSVR"), size=1, linetype = "dashed") +
  geom_line(aes(x=time_date, y=predict_starima, color="STARIMA"), size=1, linetype = "dashed") +
  geom_line(aes(x=time_date, y=predict_arima, color="ARIMA"), size=1, linetype = "dashed") +
  geom_line(aes(x=time_date, y=predict_stgcn, color="STGCN"), size=1, linetype = "dashed") +
  geom_line(aes(x=time_date, y=predict_tgcn, color="TGCN"), size=1, linetype = "dashed") +
  scale_color_manual(name = "Type",
                     values = c("Actual" = "#1e23b3", "STSVR" = "#63e0ff", "STARIMA" = "#2fad6e", "TSVR" = "#25b7db", "ARIMA" = "#1a633f")) +
  labs(title="ST-SVR vs STARIMA Prediction", subtitle = mse_label, y="Accidents") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

compare_plot
# ggsave(file = "../Data/Layout/time_based_two_model_compare.png", compare_plot, width = 8, height = 6, dpi = 300)
```

```{r}
ggsave(file = "../Data/Layout/SpatioTemporalCompare.png", arrangeGrob(grobs = c(area_compare, compare_plot), ncol = 2), width = 15, height = 6, dpi = 300)
```
